### ISSUE TITLE
updating npm module with new release?

### ISSUE THREAD

**Issue by ianhuynh** [logzio/winston-logzio#10]
Hello, will there be an updated NPM module released to npmjs.org soon?   The last published version was 8 months ago

Thanks

**Comment by donaldpipowitch** [comment]
@gillyb Hi, can you please publish a new version. The current README is misleading as it recommends the use of `flush()` which is not published.

**Comment by AlonMiz** [comment]
@donaldpipowitch @ianhuynh 
Updated, thanks.

**Comment by donaldpipowitch** [comment]
Sweet! Thank you.
