### ISSUE TITLE
Add support for winston 3.x

### ISSUE THREAD

**Issue by brentonhouse** [logzio/winston-logzio#15]
Support using winston 3.x

**Comment by idohalevi** [comment]
@brentonhouse 
Thank you, we are working on it. I'll close this once winston 3.x is available.

**Comment by dkontorovskyy** [comment]
@idohalevi do you have any approximate dates for this update?

**Comment by idohalevi** [comment]
@dkontorovskyy 
Sorry for the delay, we had some holidays and I had some other projects to take care of. I will try to do it by the end of next week. If it is urgent or you think it is a quick fix feel free to send us PR

**Comment by idohalevi** [comment]
@brentonhouse @dkontorovskyy 
We released a new version for Winston3.x
