### ISSUE TITLE
type declaration file

### ISSUE THREAD

**Issue by LoganRsk** [logzio/winston-logzio#16]
Heya guys, I've implemented logzio in my current project and I enjoy how easy it was to set up. But I've got a request, I'm using typescript and typescript works better when there are type declaration files.
Would it be possible for you to add one? :)

**Comment by idohalevi** [comment]
@LoganRsk 
I'm glad to hear. I would add it to our todo list but I can't give you any time estimation at the moment

**Comment by idohalevi** [comment]
@LoganRsk 
Hi, I'm sorry but it will take us some time to get to it. Do you feel like sending us a PR for this?

**Comment by shakedlokits** [comment]
Also need this 🙉
