### ISSUE TITLE
`npm test` blocks forever

### ISSUE THREAD

**Issue by adrukh** [logzio/winston-logzio#2]
`$ npm test` produces the following output:

```
> winston-logzio@1.0.0 test ........./winston-logzio
> mocha -w




  winston-logzio
    send string as log message
warn: Just a test message
      ✓ builds the log object properly


  1 passing (14ms)
```

and hangs indefinitely.
node v4.2.4, npm 2.14.12 on OSX 10.11.2

My gut feeling is that this has to do with winston transport socket left open and occupying the event loop, looking for more guidance here as I'm testing logzio implementation in my project.

**Comment by gillyb** [comment]
You're probably right, and i'll try to fix this asap.
In the meantime you can still use it. Even though the tests hang, they still pass, as you can see, and the logger works. We even have a few clients using it regularly in production.

**Comment by adrukh** [comment]
Clarifying as I got deeper on this - `npm test` invokes `mocha -w`, which in turn pauses and reruns when a relevant file changes. So the hang here is intentional, I think.
There is an issue here still, but it is not detectable by `mocha` as without `-w` the test suite completes successfully.

My project uses `winston-logzio` and is tested with `tape`, which seems to be more sensitive than `mocha` and hangs in my test suites. I found the issue to revolve around the buffer-emptying timer of `logzio-nodejs` and proposed a fix, please take a look at https://github.com/logzio/logzio-nodejs/pull/8

I would like to see this propagated to `winston-logzio`, as winston transport `close()` needs to be passed downstream and trigger clearing of the timer.

Thanks!

**Comment by gillyb** [comment]
Closing, since this doesn't happen anymore. I removed the `-w` from the `npm test` script.
Thanks.
