### ISSUE TITLE
Why log method expects to have smth under Symbol.for('splat') field?

### ISSUE THREAD

**Issue by dkontorovskyy** [logzio/winston-logzio#20]
https://github.com/logzio/winston-logzio/blob/master/lib/winston-logzio.js#L29

My log is stringified JSON. It has nothing inside ```  info[Symbol.for('splat')] ```, instead I have my stringified message under ``` info[Symbol.for('message')] ```. How to make this work for me?

**Comment by idohalevi** [comment]
@dkontorovskyy 
Sorry for the late response, I just wanted to test your example before getting back to you with an answer. I see that the message is under `info[Symbol.for('message')]` but also under `message`, we use `info[Symbol.for('splat')]` only to extract the error if needed.

**Comment by dkontorovskyy** [comment]
Adding additional info:

So, I'm initializing logger this way: 

```
createLogger({
            format: this.formatLogs(settings), // Create log format
            level: settings.level,
            transports: Logger.initTransports(settings.transports), // Initialize winston transports (file, console logzio)
        });

```

So all my problems from ``` formatLogs ```. This method is adding additional info to message and stringifying that object, cos format method should return string.

```
private static formatLogs(settings) {
        return format.combine(
            format.timestamp(),
            format.printf(info => {
                // Retrieve timestamp, log message, log context and extra data
                const { timestamp, level, message, context, ...args } = info;

                // Minimal log structure
                const logMessage: ILogMessage = {
                    '@timestamp': timestamp,
                    appName: settings.appName, // static info
                    context: context,
                    dc: settings.datacenter,  // static info
                    host: hostname(),   // os.hostname()
                    logger: Logger.LOGGER_NAME, // static info
                    logLevel: level, 
                    message,  // log message
                    module: settings.appName, // static info
                    module_version: settings.moduleVersion // static info
                };

                return JSON.stringify(logMessage);
            })
        );
    }
```

**Comment by dkontorovskyy** [comment]
It will work. I'm doing it with JSON message. Or you mean difference is cos my message is stringified?

**Comment by idohalevi** [comment]
Yours is working but there is too many duplicates value in the assign. When I try to reduce it, I can't seem to find an official way to where all the metadata is located. For example, If you try to just log a json object the additional keys (all those that are not `message`) will not be under `splat('message')`
