### ISSUE TITLE
Sample code for 3.x is not valid

### ISSUE THREAD

**Issue by brentonhouse** [logzio/winston-logzio#22]
The sample code listed in the readme.md file is not valid code:

```
const logger = createLogger(winston.Logger)({
  transports: [logzioWinstonTransport]
]);
```

There is an extra `]`, a missing `}` and `createLogger` is an undefined function.

It seems like it would be something like this:

```
winston.add(new LogzioWinstonTransport(options));
```

but this doesn't seem to work either.

**Comment by idohalevi** [comment]
@brentonhouse 
It was a typo mistake I will fix. try:
`const logger = createLogger({
    transports: [logzioWinstonTransport]
});`

**Comment by brentonhouse** [comment]
With that, it gives an error:

```
Invalid transport, must be an object with a log method.
```

**Comment by brentonhouse** [comment]
Thanks!!
