### ISSUE TITLE
Cannot override the type field

### ISSUE THREAD

**Issue by facundofarias** [logzio/winston-logzio#29]
I am declaring the winston logger in this way:

```
const logzioWinstonTransport = new LogzioWinstonTransport({
  level: 'info',
  name: 'winston_logzio',
  token: '__YOUR_API_TOKEN__',
});
```

But it doesn't make what I put on the name variable, I am always receiving the type as *nodejs*:
![image](https://user-images.githubusercontent.com/2700564/53525237-95fdc680-3ae1-11e9-8381-c24756ab37c9.png)

Any idea how to configure this? It's important because in all the other services (using other loggers) this is working properly, and we use this field to filter out.

Thanks a lot!

**Comment by facundofarias** [comment]
Also, the field level also looks weird:
![image](https://user-images.githubusercontent.com/2700564/53525473-25a37500-3ae2-11e9-8c53-a7a62474526b.png)

**Comment by facundofarias** [comment]
Sorry, I found the issue, and it's on this package instead: **logzio-nodejs**.
Will move the issue.

Thanks.

**Comment by facundofarias** [comment]
Never mind, I found the problem (maybe we can add this to the docs):

```
const logzioWinstonTransport = new LogzioWinstonTransport({
  level: 'info',
  type: 'MyCustomType',
  token: '__YOUR_API_TOKEN__',
});
```

and then it worked. Apologies for the inconveniences.

**Comment by idohalevi** [comment]
@facundofarias 
I agree the docs a bit misleading. Thank you for the feedback
