### ISSUE TITLE
Logging token is not valid

### ISSUE THREAD

**Issue by baba43** [logzio/winston-logzio#37]
I've added the `Token` found in the Account Settings to this snippet but the logging always fails.

```
const logzioTransport = new LogzioWinstonTransport({
  level: 'info',
  token: '...',
})
```

Error:
```
logzio-logger error: Error: There was a problem with the request.
Response: 401: 401 - "Logging token is not valid" Error: There was a problem with the request.
Response: 401: 401 - "Logging token is not valid"
```

What am I missing?

**Comment by idohalevi** [comment]
@baba43 Can you describe where you took the token from?

**Comment by baba43** [comment]
@idohalevi `Settings → General → Account Settings → Token`.

**Comment by idohalevi** [comment]
@baba43 It's hard to tell. If you'll contact our support they will help you in a matter of minutes. From what I can tell you are using the right token so maybe it's just a type

**Comment by baba43** [comment]
@idohalevi thank you. I just did it.

It came out that the host (for the listener) must be changed according to my Account settings.

My suggestion is that you add a note for this to your readme or even link this awesome help page:
https://app.logz.io/#/dashboard/data-sources/nodejs-winston
