### ISSUE TITLE
Typescript error compiling winston-logzio.d.ts

### ISSUE THREAD

**Issue by ewh** [logzio/winston-logzio#43]
I'm seeing a TS compiler error in winston-logzio.d.ts. I'm _very_ new to TS so it could be something I'm doing. Here are my compiler settings:
```JSON
"compilerOptions": {
    "outDir": "build",
    "target": "ES2019",
    "module": "CommonJS",
    "moduleResolution": "Node",
    "esModuleInterop": true
}
```
This code `declare class LogzioWinstonTransport extends Transport` has this error: `"Type 'typeof TransportStream' is not a constructor function type.ts(2507)"`. It seems to come from this import: 
```typescript
import * as Transport from "winston-transport";
```
Changing the import like this resolves the issue:
```typescript
import Transport from "winston-transport";
```
I think using `import *` should not be used to import something later used as a constructor. This [conversation](https://stackoverflow.com/a/29598404) may be relevant.

**Comment by idohalevi** [comment]
@ewh thank you for reporting this issue. @ronish31 @Doron-Bargo

**Comment by ronish31** [comment]
Hi @ewh,
Did you import 'winston-logzio' this way:
import * as LogzioWinstonTransport from 'winston-logzio' ?

**Comment by ewh** [comment]
Hi @ronish31! I didn't notice your response until now.

I'm importing `winston-logzio` like this:
```
import LogzioWinstonLib from "winston-logzio";
```
Does that seem reasonable?

Thank you so much!

**Comment by ewh** [comment]
@ronish31 @skgbafa This looks fantastic!

Do you know when this fix will be released to NPMJS?

Thanks!

**Comment by ronish31** [comment]
@ewh 
In a few days the documentation will be approved and then i'll release the new version to npm.

**Comment by ronish31** [comment]
@ewh 
Uploaded to npm.
https://github.com/logzio/winston-logzio/pull/45
