### ISSUE TITLE
Prevent winston-logzio from logging to console

### ISSUE THREAD

**Issue by mrmayfield** [logzio/winston-logzio#5]
I am currently using this module and can't figure out how to turn off logs to the console.
```
var winston = require('winston');
var logzioWinstonTransport = require('winston-logzio');

var loggerOptions = {
  token: config.LOGZIO_API_KEY
};

winston.add(logzioWinstonTransport, loggerOptions);

winston.log('info', `${responseName}`, response);
```

Then to my console I get something like

`info: List Identity Response error=null, response=[], success=true, id=undefined, firstName=undefined, lastName=undefined`

How can I turn off that logging? Thanks!

**Comment by gillyb** [comment]
By default, winston logs to the console. You can easily remove this by adding this line  
```js
winston.remove(winston.transports.Console);
```
just after configuring winston
