### ISSUE TITLE
Publish latest to npm?

### ISSUE THREAD

**Issue by johnpeb** [logzio/winston-logzio#7]
We're depending on winston-logzio 1.0.1 but somehow it's still depending on "logzio-nodejs": "^0.3.6". Can the latest be published so that we can use "logzio-nodejs": "0.4.1"? Thanks!

**Comment by gillyb** [comment]
Hi, truth be told, I don't know why the newest version didn't include logzio-node 0.4.1, since it was defined like that in the github repo.
Anyways, I bumped the version and republished to npm, so now if u update you'll get the latest.
