### ISSUE TITLE
Uncaught Exception (uce) log entry is lost when process exits 

### ISSUE THREAD

**Issue by ianhuynh** [logzio/winston-logzio#8]
When an uce occurs, it looks like the async logger also gets killed (before it flushes all messages in the buffer) when process exits  -- resulting in lost messages
```
process.on('uncaughtException', function (err) {
  logger.error("UncaughtException : ",   err);  <<<< THIS IS NEVER LOGGED
  });
  process.exit(1);
})
```

if you are willing to entertain a PR for a patch, we'd be happy to share.

**Comment by gillyb** [comment]
Sure. Pls submit a PR and we'll go over it. :)

**Comment by ianhuynh** [comment]
PR submitted.
